version: "3"
services:
    db:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        restart: unless-stopped

    ganache_cli:
        image: trufflesuite/ganache-cli:latest
        container_name: ganache_cli
        restart: unless-stopped
        ports:
            - 8545:8545
        volumes: 
            - ./ganache_data:/ganache_data
        entrypoint: 
            - node
            - /app/ganache-core.docker.cli.js
            - --deterministic
            - --db=/ganache_data
            - --mnemonic
            - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
            - --networkId
            - '5777'
            - --hostname
            - '127.0.0.1'
            - --debug



    easy-certificate:
        image: easy-certificate:latest
        container_name: node
        restart: unless-stopped
        working_dir: /app
        ports:
            - 3000:3000
            - 5000:5000
        links: 
            - ganache_cli
            - db


